(ns plr.imgs)

(def logo-map
  {"Ada"                  "ada.png"
   "APL"                  "apl.png"
   "Assembly"             "assembly.png"
   "ASP.NET"              "asp.net.jpg"
   "Shell"                "bash.png"
   "BQN"                  "bqn.svg"
   "C"                    "c.png"
   "C++"                  "cpp.png"
   "C#"                   "csharp.png"
   "Chapel"               "chapel.png"
   "Classic Visual Basic" "vb.jpg"
   "Clojure"              "clojure.png"
   "COBOL"                "cobol.png"
   "Common Lisp"          "common_lisp.png"
   "Crystal"              "crystal.svg"
   "CSS"                  "css.png"
   "Cuda"                 "cuda.png"
   "Thrust"               "thrust.png"
   "D"                    "d.png"
   "Dart"                 "dart.png"
   "Delphi"               "delphi.png"
   "Elixir"               "elixir.png"
   "Elm"                  "elm.png"
   "Emacs Lisp"           "emacs_lisp.png"
   "Erlang"               "erlang.png"
   "F#"                   "fsharp.png"
   "Fortran"              "fortran.png"
   "FoxPro"               "foxpro.png"
   "Futhark"              "futhark.png"
   "Gleam"                "gleam.svg"
   "Go"                   "go.png"
   "Groovy"               "groovy.jpeg"
   "Haskell"              "haskell.svg"
   "HTML"                 "html.svg"
   "J"                    "j.svg"
   "Java"                 "java.png"
   "JavaScript"           "javascript.png"
   "jq"                   "jq.jpg"
   "Julia"                "julia.png"
   "Jupyter Notebook"     "jupyter.png"
   "Kotlin"               "kotlin.svg"
   "LFE"                  "lfe.png"
   "Lisp"                 "lisp.png"
   "Lua"                  "lua.png"
   "Markdown"             "markdown.png"
   "Mathematica"          "mathematica.png"
   "MATLAB"               "matlab.png"
   "NewLisp"              "newlisp.jpg"
   "Nim"                  "nim.png"
   "Objective-C"          "objc.png"
   "OCaml"                "ocaml.jpg"
   "Pascal"               "pascal.png"
   "Perl"                 "perl.png"
   "PicoLisp"             "pico_lisp.png"
   "PLgpSQL"              "plgpsql.png"
   "Pharo"                "pharo.png"
   "PHP"                  "php_circle.png"
   "PowerShell"           "powershell.png"
   "PureScript"           "purescript.png"
   "Python"               "python.png"
   "q"                    "kx.png"
   "R"                    "r.png"
   "Racket"               "racket.png"
   "Reason"               "reason.jpg"
   "ReScript"             "rescript.png"
   "Ruby"                 "ruby.png"
   "Rust"                 "rust.png"
   "SAS"                  "sas.png"
   "Sass/SCSS"            "sass.png"
   "Scala"                "scala.svg"
   "Scheme"               "scheme.svg"
   "Scratch"              "scratch.png"
   "Solidity"             "solidity.svg"
   "SQL"                  "sql.png"
   "Standard ML"          "sml.png"
   "Swift"                "swift.png"
   "TypeScript"           "ts.png"
   "VBA"                  "vba.png"
   "Visual Basic"         "vb.jpg"
   "Visual Basic .NET"    "vb.jpg"
   "Vim Script"           "vim.png"
   "Vue"                  "vue.png"
   "Zig"                  "zig.svg"})

(def site-logos
  {:so       "stackoverflow.png"
   :rm       "redmonk.png"
   :tiobe    "tiobe.jpg"
   :pypl     "pypl.png"
   :ieee     "ieee.jpeg"
   :octo     "octoverse.png"
   :languish "languish.svg"
   :githut   "githut.png"
   :jb       "jetbrains.png"
   :twitter  "twitter.png"
   :google   "google.png"})