(ns plr.imgs)

(def logo-map
  {"Ada"                  "ada.png"
   "APL"                  "apl_logo.png"
   "Assembly"             "assembly_logo.png"
   "ASP.NET"              "asp.net.jpg"
   "Shell"                "bash_logo.png"
   "BQN"                  "bqn_logo.svg"
   "C"                    "c_logo.png"
   "C++"                  "cpp_logo.png"
   "C#"                   "csharp_logo.png"
   "Chapel"               "chapel.png"
   "Classic Visual Basic" "vb.jpg"
   "Clojure"              "clojure_logo.png"
   "COBOL"                "cobol.png"
   "Common Lisp"          "common_lisp.png"
   "Crystal"              "crystal_logo.svg"
   "CSS"                  "css_logo.png"
   "Cuda"                 "cuda.jpg"
   "Thrust"               "thrust_logo.jfif"
   "D"                    "d_logo.png"
   "Dart"                 "dart_logo.png"
   "Delphi"               "delphi.png"
   "Elixir"               "elixir_logo.png"
   "Elm"                  "elm_logo.png"
   "Emacs Lisp"           "emacs_lisp.png"
   "Erlang"               "erlang_logo.png"
   "F#"                   "fsharp_logo.png"
   "Fortran"              "fortran_logo.png"
   "FoxPro"               "foxpro.png"
   "Futhark"              "futhark.png"
   "Gleam"                "gleam.png"
   "Go"                   "go_logo_thin.png"
   "Groovy"               "groovy_logo.jpeg"
   "Haskell"              "haskell_logo.svg"
   "HTML"                 "html_logo.svg"
   "J"                    "j_logo.png"
   "Java"                 "java_logo.png"
   "JavaScript"           "javascript_logo.png"
   "jq"                   "jq.jpg"
   "Julia"                "julia_logo.svg"
   "Jupyter Notebook"     "jupyter_logo.png"
   "Kotlin"               "kotlin-2.svg"
   "LFE"                  "lfe.png"
   "Lisp"                 "LISP_logo.png"
   "Lua"                  "lua_logo.png"
   "Markdown"             "markdown_logo.png"
   "Mathematica"          "mathematica.png"
   "MATLAB"               "matlab_logo.png"
   "NewLisp"              "newlisp.jpg"
   "Nim"                  "nim_logo.png"
   "Objective-C"          "objc_logo.png"
   "OCaml"                "ocaml_logo.jpg"
   "Pascal"               "pascal.png"
   "Perl"                 "perl.png"
   "PicoLisp"             "pico_lisp.png"
   "PLgpSQL"              "plgpsql.png"
   "Pharo"                "pharo_logo.png"
   "PHP"                  "php_circle.png"
   "PowerShell"           "powershell_logo.png"
   "PureScript"           "purescript.png"
   "Python"               "python_logo.png"
   "q"                    "kx-logo.png"
   "R"                    "r_logo.png"
   "Racket"               "racket_logo.png"
   "Reason"               "reason.jpg"
   "ReScript"             "rescript.png"
   "Ruby"                 "ruby_logo.png"
   "Rust"                 "rust_logo.png"
   "SAS"                  "sas_logo.png"
   "Sass/SCSS"            "sass.png"
   "Scala"                "scala_logo2.png"
   "Scheme"               "scheme.svg"
   "Scratch"              "scratch.png"
   "Solidity"             "solidity_logo.svg"
   "SQL"                  "sql_logo.png"
   "Standard ML"          "sml.png"
   "Swift"                "swift_logo.png"
   "TypeScript"           "ts.png"
   "VBA"                  "vba.png"
   "Visual Basic"         "vb.jpg"
   "Visual Basic .NET"    "vb.jpg"
   "Vim Script"           "vim.png"
   "Vue"                  "vue.png"
   "Zig"                  "zig_logo.svg"})

(def site-logos
  {:so       "stackoverflow.png"
   :rm       "redmonk.png"
   :tiobe    "tiobe.jpg"
   :pypl     "pypl.png"
   :ieee     "ieee.jpeg"
   :octo     "octoverse.png"
   :languish "languish.svg"
   :githut   "githut.png"
   :jb       "jetbrains.png"
   :twitter  "twitter.png"
   :google   "google.png"})