name: ClojureScript Build and Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'src/plr/**/*.clj'
      - 'src/plr/**/*.cljs'
      - 'shadow-cljs.edn'
  # Add manual trigger option
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Set up Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: Cache yarn
      uses: actions/cache@v3
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/shadow-cljs.edn') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Install yarn deps
      run: yarn install

    - name: Install shadow-cljs
      run: yarn add --dev shadow-cljs

    - name: Build for production
      run: yarn shadow-cljs release dev

    - name: Create .nojekyll file
      run: touch public/.nojekyll

    - name: Ensure js directory exists
      run: mkdir -p public/js

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public
          CLEAN: true
